### PR TITLE
Rails 5 compatibility

### PR DESCRIPTION
**Pull request by benlovell**
A bunch of stuff required for Rails 5 compatibility.

Best reviewed on a commit-by-commit basis.

### CODE REVIEW

**Comment by boffbowsh** [comment]
`guidance-guarantee-programme-rails5` branch pushed to origin in order to run tests

**Comment by boffbowsh** [comment]
✨ 🌟 ⭐ 👍 ⭐ 🌟 ✨

**Comment by benlovell** [comment]
💟 Thanks 💟

**Comment by fofr** [comment]
😍

**Pull request merged**
