### PR TITLE
Rename preview to integration

### PR DESCRIPTION
**Pull request by alexmuller**
The preview environment is being renamed integration to better reflect its purpose.

This commit changes all user-facing instances of 'preview' to 'integration'.

I've left the CSS selectors for preview in place to preserve backwards compatibility - I'm happy to remove those if people would prefer.

### CODE REVIEW

**Comment by boffbowsh** [comment]
This will break a lot of things in Signon. We rely on the value of the label to detect the preview environment and set 2-step verification behaviour accordingly.

**Comment by boffbowsh** [comment]
There might be other apps that do this as well.

**Comment by fofr** [comment]
@boffbowsh This can be versioned as a breaking change.

The copy in those Signon emails will need to be updated too.

**Comment by boffbowsh** [comment]
This is more related to the wider move to integration from preview. These variables are set via an environment variable, and changing the value of this in the new int environment will break things. Example output from `ag environment_label`:

```
publisher/app/views/layouts/application.html.erb
4:  <% environment_style = GovukAdminTemplate.environment_style %>
5:  <%= favicon_link_tag environment_style ?
6:        "favicon-#{environment_style}.png" : "favicon.png" %>
```

`favicon-integration.png` won't exist, I don't think?

**Comment by alexmuller** [comment]
Updated to copy the preview favicon to a new name :)

(I'm sure there's lots more still to do…)

**Comment by fofr** [comment]
Many apps override the favicon with a custom one eg the [W] icon in Whitehall https://github.com/alphagov/whitehall/blob/master/app/assets/images/admin/favicon-preview.png.

That could be noted as part of the breaking change.

**Comment by fofr** [comment]
An alternative might be to update the label to "Integration" in the initialiser, this would be similar to what we do for Staging: 

```ruby
when "staging"
      environment_style = "preview"
      environment_label = "Staging"
```

See https://github.gds/gds/alphagov-deployment/blob/master/recipes/govuk_admin_template.rb

**Comment by boffbowsh** [comment]
I no longer have any objections to this PR :+1:

**Comment by fofr** [comment]
Anything holding this up now?

@alexmuller Can you rebase?

**Comment by fofr** [comment]
I've rebased this.

**Comment by alexmuller** [comment]
Thanks, sorry I missed this. I think this is good to go :+1:

**Pull request merged**
